In [101]:
import numpy as np
from scipy.optimize import minimize
np.set_printoptions(threshold='nan')

## prepare data set
- this bloc is for preparing the data matrix has_rating[i,j] 1 if a paticular user has rated a particular movie, 0. otherwise rating[i,j] real rating that given by particular users **value exist if and only if coresponding has_rating[i,j]==1
- number of users can be optain by len(names) and number of movies can be optain by len(movies)

In [102]:
import StringIO
import csv
with open('Restaurant Rating - Sheet1.csv') as f:
    s = StringIO.StringIO(f.read()) 
    reader = csv.reader(s, delimiter=',')
    raw = [row for row in reader]

def get_names(raw):
    return raw[2][2:]

def get_movies(raw):
    movies = []
    for i in range(3, len(raw)):
        movies.append(raw[i][1])
    return movies

def get_rating(raw):
    
    names = get_names(raw)
    movies = get_movies(raw)
    name_offset = 2
    movies_offset = 3
    
    n_names = len(names)
    n_movies = len(movies)

    has_rating = np.zeros((n_names, n_movies))
    rating = np.zeros((n_names, n_movies))
    
    for ir in range(n_movies):
        
        this_row = raw[movies_offset + ir]

        for ip in range(n_names):
            
            this_cell =  this_row[name_offset + ip]
            hr = this_cell.isdigit()
            has_rating[ip, ir] = 1 if hr else 0
            if hr:
                rating[ip, ir] = int(this_cell)
                
    return names, movies, has_rating, rating

names, movies, has_rating, rating = get_rating(raw)

print "name", names
print "movies", movies
print "has_rating", has_rating.T
print "rating", rating.T

name ['Piti', 'Meena', 'Pitoon', 'Sohum', 'Sam', 'Keng', 'O', 'Yok', 'Kitty', 'Time', 'Robroo', 'Peem', 'Chanon', 'Ohm', 'Sun', 'Tii', 'Tow', 'John', 'Mint', 'Opal', 'Kelly', 'Jay', 'Sharik', 'Ou', 'PJ', 'Punawit', 'Martin', 'Ploy', 'Majeed', 'Bossy', 'Sea', 'Pan', 'Ice', 'Karn', 'May', 'Rin', 'Peter', 'Ham', 'Benz', 'Billy', 'Kanat', 'Sam', 'Boss', 'Best']
movies ['Mai-tok-mai-tak', 'Puttharaksa', 'Big Mamma', 'Seefah', 'Music Square', 'Mamma Mia', 'Srijan', 'Steak House', 'Anya', 'Chicky Chic', 'Loong Nuad', 'Nong Na', 'Shabu Nangnai', 'Buri-yummy', 'Gin-na', 'Fong-nom', 'Fresh box', 'Buta grill', 'Lodiham', 'Kao-pun', 'Sutharos', 'Hua-seng-hong', 'Jok at 3 AM', 'RIT', 'Hong nung len', 'slum bar', 'Ban-nam', 'Mango Bar', 'Sri suwan', 'Herb Garden', 'Best Bar', 'Princess Cafe', 'Hachi Ban', 'Vietnam Hut', 'Chi-see', 'J-Class', 'Bon chon', 'Sunrise Taco', 'Beach Bar', 'Brew & Bev', 'Bake & Bite']
has_rating [[ 0.  0.  1.  0.  0.  1.  1.  1.  0.  1.  1.  1.  0.  1.  1.  1.  1.  0.
   1.

## Implementation of Detail Mean Normalization
- the seection below here is implemented to handle the case of newly added user that has never rated any movie before 
- notice that in our data set we have Eve who never rate any movie so we can think of her as newly added user

In [103]:
# init the average matrix
average = np.zeros((len(movies),1))

# find average value for each row 
for i in range (0,len(movies)):
    sum_each_row = 0
    count_num = 0
    
    for j in range (0,len(names)):
        
        if has_rating.T[i][j] == 1:
            sum_each_row = sum_each_row + rating.T[i][j]
            count_num = count_num+1
            
    average[i][0] = sum_each_row/count_num
    
print average

[[ 3.19230769]
 [ 3.42424242]
 [ 4.14285714]
 [ 3.59090909]
 [ 3.75      ]
 [ 4.02941176]
 [ 3.        ]
 [ 2.91666667]
 [ 3.84848485]
 [ 2.60526316]
 [ 3.21875   ]
 [ 3.77777778]
 [ 2.63636364]
 [ 3.25806452]
 [ 2.92857143]
 [ 3.23076923]
 [ 4.07407407]
 [ 3.45454545]
 [ 3.16666667]
 [ 2.76470588]
 [ 3.35294118]
 [ 3.19047619]
 [ 3.69230769]
 [ 3.        ]
 [ 3.14285714]
 [ 1.85714286]
 [ 4.19230769]
 [ 3.2       ]
 [ 3.39285714]
 [ 3.13793103]
 [ 3.125     ]
 [ 2.89285714]
 [ 3.74074074]
 [ 4.17647059]
 [ 2.80952381]
 [ 3.25      ]
 [ 4.05882353]
 [ 3.81818182]
 [ 4.        ]
 [ 3.2       ]
 [ 3.4       ]]


# running data after Implementation of Detail Mean Normalization
- on the section below here we re-run our main again with the new rating matrix  

In [104]:
print "original rating",rating.T
# re-init value for rating matrix
for i in range (0,len(movies)):
    for j in range (0,len(names)):
        if has_rating.T[i][j] == 1:
            rating.T[i][j] = rating.T[i][j] - average[i]
print "rating after DMN",rating.T 

original rating [[ 0.  0.  2.  0.  0.  2.  2.  3.  0.  3.  3.  5.  0.  3.  2.  3.  3.  0.
   2.  3.  3.  3.  0.  2.  0.  0.  0.  4.  0.  3.  4.  0.  0.  3.  4.  0.
   0.  0.  4.  4.  4.  0.  4.  5.]
 [ 4.  0.  4.  4.  4.  3.  4.  3.  0.  3.  0.  4.  3.  4.  3.  4.  4.  3.
   3.  3.  3.  3.  3.  3.  0.  0.  0.  3.  3.  0.  4.  4.  4.  0.  4.  3.
   0.  0.  1.  4.  3.  0.  4.  4.]
 [ 0.  4.  0.  5.  5.  0.  0.  0.  4.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  4.  4.
   0.  3.  0.  0.  0.  0.  0.  0.]
 [ 0.  2.  4.  4.  5.  0.  4.  3.  0.  5.  0.  4.  3.  0.  0.  4.  0.  3.
   0.  0.  0.  0.  4.  2.  0.  4.  0.  3.  0.  2.  0.  0.  0.  0.  3.  0.
   3.  4.  0.  4.  0.  0.  5.  4.]
 [ 2.  0.  0.  0.  3.  4.  0.  4.  4.  4.  4.  0.  0.  0.  4.  4.  5.  0.
   5.  0.  4.  3.  0.  2.  0.  5.  0.  3.  0.  0.  4.  0.  0.  4.  5.  4.
   0.  0.  0.  2.  4.  0.  4.  3.]
 [ 3.  4.  0.  5.  5.  0.  4.  4.  0.  4.  5.  5.  3.  5.  3.  5.  4.

## Getting the best weight
- start Linear Regression class below here

In [105]:
class LinearRegression: 
    
     # init all the data so it can easily accessed by all methods
    def __init__(self,has_rating,real_rating,fea,lamda,names,movies,theta,x):
        
        #has_rating and real_rating here are already transposed
        self.has_rating = has_rating
        self.real_rating = real_rating
        
        self.fea=fea
        self.lamda=lamda
        self.names = names
        self.movies = movies
        self.num_names = len(names)
        self.num_movies = len(movies) 
        self.theta = theta
        self.x = x
    
    def sum_x(self,i,k,lamda):
        
        sum_x_value = 0 
        
        for j in range (0,self.num_names):
            if self.has_rating[i][j] == 1:
                sum_x_value = sum_x_value+(np.dot(self.theta[j].T,self.x[i]) - self.real_rating[i][j])*self.theta[j][k]
     
        #print "x", sum_x_value      
        return sum_x_value
    
    
    def sum_theta(self,j,k,lamda):
        
        sum_theta_value = 0
        
        for i in range (0,self.num_movies):
            if self.has_rating[i][j] == 1:
                sum_theta_value = sum_theta_value+(np.dot(self.theta[j].T,self.x[i]) - self.real_rating[i][j])*self.x[i][k]
        #print "theta", sum_theta_value
        return sum_theta_value
                
                
                
                
    #this function will seek for the x and thata that can meet the local minimum of the function
    def gradient_descent(self,alpha,lamda):
        
        # init keep_array for both x and theta
        keep_x = np.zeros((self.num_movies,self.fea))
        keep_theta = np.zeros((self.num_names,self.fea))
        keep_x = self.x
        keep_theta = self.theta
        print keep_theta
        print keep_x
        print self.real_rating
        
        for times in range(0,1000):
            #print "time", times
            #re-assign value to self.x and self.theta
            self.x = keep_x
            self.theta = keep_theta
            
            #set the value of x
            for i in range (0,self.num_movies):
                for k in range (0,self.fea):
                    
                    keep_x[i][k] = self.x[i][k] - alpha*(self.sum_x(i,k,lamda)+lamda*self.x[i][k])
        
            #return self.x
            
            
            #set the value of theta
            for j in range (0,self.num_names):
                for k in range (0,self.fea):
                    
                    keep_theta[j][k] = self.theta[j][k] - alpha*(self.sum_theta(j,k,lamda)+lamda*self.theta[j][k])
            
        return self.x,self.theta

In [106]:
number_feature = 4
#next time try np.zeros for both theta and x
guess_theta = np.random.uniform(0.01,5,[len(names),number_feature])
guess_x = np.random.uniform(0.01,1,[len(movies),number_feature])

linear_obj = LinearRegression(has_rating.T,rating.T,number_feature,0.01,names,movies,guess_theta,guess_x)
result_x, result_theta = linear_obj.gradient_descent(0.001,0.01)

print "x", result_x
print "theta", result_theta

[[ 3.29375745  1.03282613  2.21811719  4.82892391]
 [ 4.67403228  4.71343165  3.05435296  2.10985594]
 [ 3.45565514  2.71798074  3.18160523  4.47316328]
 [ 4.12684932  1.54653491  4.4014566   1.96504386]
 [ 0.73235859  1.4334849   3.47112853  1.83273904]
 [ 4.68642896  3.15360495  3.20504491  3.22165707]
 [ 4.26669913  1.14477236  2.98860702  3.35307157]
 [ 0.39213374  3.63963854  2.06675178  2.80845005]
 [ 1.71036014  4.03897889  4.09071021  2.77293678]
 [ 4.82144119  4.98598844  4.83931273  4.47057688]
 [ 4.86307009  4.81011039  3.34472477  1.26224407]
 [ 2.66771868  3.98290715  2.95558137  0.89508928]
 [ 0.67394805  4.70597317  2.17055497  3.66943973]
 [ 0.18717843  3.66095028  1.86251695  4.14233764]
 [ 3.17912881  1.94957593  0.3567318   3.83821942]
 [ 2.02330264  0.08020303  1.61892729  4.55799552]
 [ 3.19971307  2.1116745   2.57980337  0.5609505 ]
 [ 0.84266219  3.72471827  3.17008865  0.72535245]
 [ 4.10218741  4.18198514  0.48964245  0.03534592]
 [ 0.73454237  0.59641298  2.06

In [107]:
out = np.zeros((len(movies),len(names)))
for i in range(0,len(movies)):
            for j in range(0,len(names)):
                    out[i][j] = float("{0:.2f}".format(float((np.dot(result_theta[j].T,result_x[i])))+float((average[i]))))
print out

[[  3.27   3.17   1.78   3.77   4.27   3.19   3.79   3.53   3.61   3.18
    3.11   3.85   2.38   2.67   2.5    3.28   3.6    2.45   2.12   2.98
    3.09   3.1    2.58   2.67   3.31   3.08   3.45   3.08   2.95   2.6
    3.49   4.03   2.88   3.22   3.42   3.14   4.49   3.34   3.72   4.06
    3.31   3.52   3.44   3.25]
 [  3.87   2.97   3.3    3.4    3.96   3.3    3.65   3.51   3.52   3.37
    2.87   3.35   3.31   3.56   3.32   3.76   3.19   3.01   2.6    3.73
    2.81   3.53   3.06   3.15   3.41   3.5    3.78   3.05   3.38   2.77
    3.56   3.62   3.12   3.66   3.73   3.23   3.8    3.22   3.27   3.55
    3.23   3.49   3.63   3.61]
 [  4.4    3.6    1.65   4.76   4.85   3.39   5.23   4.17   4.01   3.47
    3.64   4.35   2.05   2.43   3.07   4.77   4.34   1.55   1.81   3.79
    3.11   3.86   3.01   3.11   3.67   3.19   3.95   3.46   2.77   3.49
    4.58   4.85   4.19   4.29   4.09   4.28   5.77   3.66   4.97   5.31
    3.48   4.78   4.74   4.77]
 [  4.57   2.89   3.75   3.59   4.57   3.53 

Display code from aj piti homework

In [108]:
from IPython.display import HTML

class TableCell:
    
    def __init__(self, text, tc=None, color=None):
        self.text = text
        self.tc = tc
        self.color = color
    
    def to_html(self):
        return '<td>%s</td>'%self.text
    
def maketable(rating, has_rating, guess, restaurants, names):
    n_rests = len(restaurants)
    n_names = len(names)
    tab = np.empty((n_rests+1, n_names+1),dtype='object')
    #print tab.shape

    for irest in range(n_rests):
        tab[irest+1,0] = restaurants[irest]

    for iname in range(n_names):
        tab[0,iname+1] = names[iname]

    for irest in range(n_rests):
        for iname in range(n_names):
            if not has_rating[iname, irest]:
                tab[irest+1, iname+1] = TableCell('<span style="color:red">%3.2f</span>'%(guess[iname, irest]))
            else:
                tab[irest+1, iname+1] = TableCell('<span style="color:blue">%3.2f</span><span style="color:red">(%3.2f)</span>'%(rating[iname, irest], guess[iname, irest]))
    #now convert tab array to nice html table
    nrow, ncol = tab.shape
    t = []
    t.append('<table>')
    for irow in range(nrow):
        t.append('<tr>')
        for icol in range(ncol):
            cell = tab[irow,icol]
            if cell is not None:
                if isinstance(cell,TableCell):
                    t.append(tab[irow, icol].to_html())
                else:
                    t.append('<td>')
                    t.append(tab[irow, icol])
                    t.append('</td>')
            else:
                t.append('<td></td>')
        t.append('</tr>')  
    t.append('</table>')
    return '\n'.join(t)

In [109]:
#HTML(maketable(rating.T, has_rating.T, out, movies, names))