In [351]:
import numpy as np
from scipy.optimize import minimize
np.set_printoptions(threshold='nan')

## prepare data set
    - this bloc is for preparing the data matrix has_rating[i,j] 1 if a paticular user has rated a particular movie, 0 otherwise. Rating[i,j] real is rating that given by particular users **value exist if and only if coresponding has_rating[i,j]==1
    - number of users can be optain by len(names) and number of movies can be optain by len(movies)

In [352]:
import StringIO
import csv
with open('resource - Sheet1 (2).csv') as f:
    s = StringIO.StringIO(f.read()) 
    reader = csv.reader(s, delimiter=',')
    raw = [row for row in reader]

def get_names(raw):
    return raw[2][2:]

def get_movies(raw):
    movies = []
    for i in range(3, len(raw)):
        movies.append(raw[i][1])
    return movies

def get_rating(raw):
    
    names = get_names(raw)
    movies = get_movies(raw)
    name_offset = 2
    movies_offset = 3
    
    n_names = len(names)
    n_movies = len(movies)

    has_rating = np.zeros((n_names, n_movies))
    rating = np.zeros((n_names, n_movies))
    
    for ir in range(n_movies):
        
        this_row = raw[movies_offset + ir]

        for ip in range(n_names):
            
            this_cell =  this_row[name_offset + ip]
            hr = this_cell.isdigit()
            has_rating[ip, ir] = 1 if hr else 0
            if hr:
                rating[ip, ir] = int(this_cell)
                
    return names, movies, has_rating, rating

names, movies, has_rating, rating = get_rating(raw)

print "name", names
print "movies", movies
print "has_rating", has_rating.T
print "rating", rating.T

name ['Alice', 'Bob', 'Carol', 'Dave', 'eve', 'time']
movies ['love', 'Romance', 'Cute', 'Nonstop', 'sword', 'iron man', 'the inturn']
has_rating [[ 1.  1.  1.  1.  0.  0.]
 [ 1.  0.  0.  1.  0.  0.]
 [ 0.  1.  1.  0.  0.  0.]
 [ 1.  1.  1.  1.  0.  0.]
 [ 1.  1.  1.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  1.  0.  1.]]
rating [[ 5.  5.  0.  0.  0.  0.]
 [ 5.  0.  0.  0.  0.  0.]
 [ 0.  4.  0.  0.  0.  0.]
 [ 0.  0.  5.  4.  0.  0.]
 [ 0.  0.  5.  0.  0.  5.]
 [ 0.  0.  0.  0.  5.  0.]
 [ 3.  0.  0.  3.  0.  3.]]


## Implementation of Detail Mean Normalization
    - the seection below here is implemented to handle the case of newly added user that has never rated any movie before 
    - notice that in our data set we have Eve who never rate any movie so we can think of her as newly added user

In [353]:
# init the average matrix
average = np.zeros((len(movies),1))

# find average value for each row 
for i in range (0,len(movies)):
    sum_each_row = 0
    count_num = 0
    
    for j in range (0,len(names)):
        
        if has_rating.T[i][j] == 1:
            sum_each_row = sum_each_row + rating.T[i][j]
            count_num = count_num+1
            
    average[i][0] = sum_each_row/count_num
    
print average

[[ 2.5 ]
 [ 2.5 ]
 [ 2.  ]
 [ 2.25]
 [ 2.5 ]
 [ 5.  ]
 [ 3.  ]]


# running data after Implementation of Detail Mean Normalization
    - on the section below here we re-run our main again with the new rating matrix  

In [354]:
print "original rating",rating.T

# re-init value for rating matrix
for i in range (0,len(movies)):
    for j in range (0,len(names)):
        if has_rating.T[i][j] == 1:
            rating.T[i][j] = rating.T[i][j] - average[i]
print "rating after DMN",rating.T 

original rating [[ 5.  5.  0.  0.  0.  0.]
 [ 5.  0.  0.  0.  0.  0.]
 [ 0.  4.  0.  0.  0.  0.]
 [ 0.  0.  5.  4.  0.  0.]
 [ 0.  0.  5.  0.  0.  5.]
 [ 0.  0.  0.  0.  5.  0.]
 [ 3.  0.  0.  3.  0.  3.]]
rating after DMN [[ 2.5   2.5  -2.5  -2.5   0.    0.  ]
 [ 2.5   0.    0.   -2.5   0.    0.  ]
 [ 0.    2.   -2.    0.    0.    0.  ]
 [-2.25 -2.25  2.75  1.75  0.    0.  ]
 [-2.5  -2.5   2.5   0.    0.    2.5 ]
 [ 0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.  ]]


## Getting the best weight
    - start Linear Regression class below here

In [355]:
class LinearRegression: 
    
     # init all the data so it can easily accessed by all methods
    def __init__(self,has_rating,real_rating,fea,lamda,names,movies,theta,x):
        
        #has_rating and real_rating here are already transposed
        self.has_rating = has_rating
        self.real_rating = real_rating
        self.fea=fea
        self.lamda=lamda
        self.names = names
        self.movies = movies
        self.num_names = len(names)
        self.num_movies = len(movies) 
        self.theta = theta
        self.x = x
    
    #this function is use to find the gradient value for x 
    def sum_x(self,i,k,lamda):
        
        sum_x_value = 0 
        
        for j in range (0,self.num_names):
            if self.has_rating[i][j] == 1:
                sum_x_value = sum_x_value+(np.dot(self.theta[j].T,self.x[i]) - self.real_rating[i][j])*self.theta[j][k]         
        
        return sum_x_value
    
    #this function is use to find the gradient value for theta
    def sum_theta(self,j,k,lamda):
        
        sum_theta_value = 0
        
        for i in range (0,self.num_movies):
            if self.has_rating[i][j] == 1:
                sum_theta_value = sum_theta_value+(np.dot(self.theta[j].T,self.x[i]) - self.real_rating[i][j])*self.x[i][k]
        
        return sum_theta_value
                
                
                
                
    #this function will seek for the x and thata that can meet the local minimum of the function
    def gradient_descent(self,alpha,lamda):
        
        # init keep_array for both x and theta
        keep_x = np.zeros((self.num_movies,self.fea))
        keep_theta = np.zeros((self.num_names,self.fea))
        keep_x = self.x
        keep_theta = self.theta
        
        #for-loop here is used for allowing the convergent of gradient value
        for times in range(0,10000):
           
            #re-assign value to self.x and self.theta
            self.x = keep_x
            self.theta = keep_theta
            
            #set the value of x
            for i in range (0,self.num_movies):
                for k in range (0,self.fea):
                    
                    keep_x[i][k] = self.x[i][k] - alpha*(self.sum_x(i,k,lamda)+lamda*self.x[i][k])
                    
            #set the value of theta
            for j in range (0,self.num_names):
                for k in range (0,self.fea):
                    
                    keep_theta[j][k] = self.theta[j][k] - alpha*(self.sum_theta(j,k,lamda)+lamda*self.theta[j][k])
            
            #every 10000 time we reduce the step size
            if times == 9000:
                alpha = alpha/10
            
        return self.x,self.theta

## Calling linear regression class

In [356]:
#set the number of feature 
number_feature = 5

#init small guessing value for both theta and x
guess_theta = np.random.uniform(0.01,1,[len(names),number_feature])
guess_x = np.random.uniform(0.01,1,[len(movies),number_feature])

#get object from linear regression class
linear_obj = LinearRegression(has_rating.T,rating.T,number_feature,0.01,names,movies,guess_theta,guess_x)

#get return from gradient descent function (minimize x and minimize theta)
result_x, result_theta = linear_obj.gradient_descent(0.05,0.01)

#show them
print "x", result_x
print "theta", result_theta

x [[  3.10302428e-01   3.24465495e-01  -2.45432524e-01   5.21045972e-01
    1.46765705e+00]
 [  3.69491169e-01   2.12738941e-01  -1.96656445e-01   5.63715853e-01
    1.45670053e+00]
 [  6.94871444e-02   6.18097406e-02  -1.42940317e-01   2.79027891e-01
    1.22667074e+00]
 [  1.06296908e-02  -1.89754763e-01   5.78401728e-01   2.82143084e-01
   -1.45930916e+00]
 [ -2.12273837e-02   4.91475891e-01   2.21890067e-01  -1.46248330e-01
   -1.60757974e+00]
 [  5.43214101e-03   4.01998846e-03   8.90300031e-03  -1.46598555e-06
    7.51314619e-04]
 [  1.21032453e-03   1.30786080e-04   2.72538092e-03  -1.27026244e-03
    5.37307566e-04]]
theta [[  2.31407248e-01   2.67856171e-02  -2.64626482e-01   3.10572673e-01
    1.49393095e+00]
 [  9.89500755e-02   6.84944721e-02  -2.00934725e-01   3.26663062e-01
    1.51672447e+00]
 [ -6.44595513e-02  -2.96679901e-01   5.86209227e-01   1.51451811e-01
   -1.57826772e+00]
 [ -4.12805497e-01  -3.16979612e-01   1.00620944e-01  -7.32027491e-01
   -1.26477490e+00]
 

## Output array

In [357]:
#out array is the final guessing value from minimize x and theta
out = np.zeros((len(movies),len(names)))

for i in range(0,len(movies)):
            for j in range(0,len(names)):
                    out[i][j] = float("{0:.2f}".format(float((np.dot(result_theta[j].T,result_x[i])))+float((average[i]))))
print out

[[ 5.    5.    0.    0.01  2.51  0.57]
 [ 4.99  4.98  0.08  0.01  2.51  0.54]
 [ 3.97  3.99 -0.    0.18  2.    0.31]
 [ 0.    0.    4.99  4.    2.25  4.24]
 [ 0.    0.    5.    4.52  2.5   4.99]
 [ 5.    5.    5.    5.    5.    5.  ]
 [ 3.    3.    3.    3.    3.    3.  ]]


## Display as Table
    -Code below here is use for display the output as table so it is easier to compare the outcome to the real rating

In [358]:
from IPython.display import HTML

class TableCell:
    
    def __init__(self, text, tc=None, color=None):
        self.text = text
        self.tc = tc
        self.color = color
    
    def to_html(self):
        return '<td>%s</td>'%self.text
    
def maketable(rating, has_rating, guess, restaurants, names,average):
    n_rests = len(restaurants)
    n_names = len(names)
    tab = np.empty((n_rests+1, n_names+1),dtype='object')
    
    for irest in range(n_rests):
        tab[irest+1,0] = restaurants[irest]

    for iname in range(n_names):
        tab[0,iname+1] = names[iname]

    for irest in range(n_rests):
        
        for iname in range(n_names):
            
            if not has_rating[irest, iname]:
                tab[irest+1, iname+1] = TableCell('<span style="color:red">%3.2f</span>'%(guess[irest, iname]))
            else:
                tab[irest+1, iname+1] = TableCell('<span style="color:blue">%3.2f</span><span style="color:red">(%3.2f)</span>'%(rating[irest, iname]+average[irest], guess[irest, iname]))
    
    #now convert tab array to nice html table
    nrow, ncol = tab.shape
    t = []
    t.append('<table>')
    for irow in range(nrow):
        t.append('<tr>')
        for icol in range(ncol):
            cell = tab[irow,icol]
            if cell is not None:
                if isinstance(cell,TableCell):
                    t.append(tab[irow, icol].to_html())
                else:
                    t.append('<td>')
                    t.append(tab[irow, icol])
                    t.append('</td>')
            else:
                t.append('<td></td>')
        t.append('</tr>')  
    t.append('</table>')
    return '\n'.join(t)

In [359]:
HTML(maketable(rating.T, has_rating.T, out, movies, names,average))

## Getting recommen list 
    -recommend movie for particular user


In [360]:
def recommend(user):
    if user in names:
        recommend_list = []
        for i in range (0,len(movies)):
            if has_rating.T[i][names.index(user)]==0:
                recommend_list.append(int(out[i][names.index(user)]))
        recommend_list.sort(reverse=True)
        print recommend_list
    else: 
        print "database does not contain this user"
        
recommend("Bob")

[5, 4, 3]
